package com.homehealthcare.compliance.foundation;

public enum ComplianceEventType {
    PATIENT_RISK_REMINDER_TRIGGERED,
    PATIENT_RISK_REMINDER_RESOLVED,
    ACKNOWLEDGMENT_MISSING,
    ACKNOWLEDGMENT_EXPIRED,
    CERTIFICATION_PERIOD_EXPIRING,
    REQUIRED_DOCUMENTATION_GAP_DETECTED,
    COMPLIANCE_STATUS_CHANGED
}
