package com.homehealthcare.compliance.foundation;

public enum ComplianceOperationGuardrail {
    PATIENT_SCOPED_AND_BRANCH_AWARE,
    MINIMUM_NECESSARY_PATIENT_CONTEXT_ONLY,
    CHECKLIST_AND_REQUIREMENT_CODES_STABLE,
    ACKNOWLEDGMENT_AND_CERTIFICATION_WINDOWS_VALIDATED,
    REMINDER_AND_PROJECTION_RECALCULATION_AUDITED,
    EXTERNAL_EVENT_CONTRACT_APPEND_ONLY
}
