package com.homehealthcare.compliance.foundation;

public enum ComplianceEntityCategory {
    COMPLIANCE_PROFILE,
    COMPLIANCE_CHECKLIST_DEFINITION,
    COMPLIANCE_CHECKLIST_RESULT,
    REQUIRED_DOCUMENTATION_REQUIREMENT,
    CONSENT_ACKNOWLEDGMENT_RECORD,
    CERTIFICATION_PERIOD_RECORD,
    PATIENT_RISK_REMINDER,
    COMPLIANCE_STATUS_PROJECTION
}
