package com.homehealthcare.compliance.foundation;

public enum Epic11ComplianceAuditAction {
    CHECKLIST_DEFINITION_SAVED("COMPLIANCE_CHECKLIST_DEFINITION_SAVED"),
    CHECKLIST_RESULT_RECALCULATED("COMPLIANCE_CHECKLIST_RESULT_RECALCULATED"),
    DOCUMENTATION_REQUIREMENT_SAVED("COMPLIANCE_DOCUMENTATION_REQUIREMENT_SAVED"),
    ACKNOWLEDGMENT_RECORDED("COMPLIANCE_ACKNOWLEDGMENT_RECORDED"),
    ACKNOWLEDGMENT_REVOKED("COMPLIANCE_ACKNOWLEDGMENT_REVOKED"),
    CERTIFICATION_PERIOD_SAVED("COMPLIANCE_CERTIFICATION_PERIOD_SAVED"),
    RISK_REMINDER_SAVED("COMPLIANCE_RISK_REMINDER_SAVED"),
    RISK_REMINDER_RESOLVED("COMPLIANCE_RISK_REMINDER_RESOLVED"),
    STATUS_PROJECTION_RECALCULATED("COMPLIANCE_STATUS_PROJECTION_RECALCULATED");

    private final String actionType;

    Epic11ComplianceAuditAction(String actionType) {
        this.actionType = actionType;
    }

    public String actionType() {
        return actionType;
    }
}
