package com.homehealthcare.documentation.foundation;

public enum DocumentationOperationGuardrail {
    ONE_ACTIVE_DOCUMENTATION_RECORD_PER_VISIT_TEMPLATE,
    DRAFT_SAVE_ALLOWS_INCOMPLETE_STATE,
    SUBMISSION_REQUIRES_ALL_REQUIRED_FIELDS,
    SUBMISSION_REQUIRES_ALL_REQUIRED_TASKS,
    ROLE_BASED_FIELD_VISIBILITY_MUST_BE_ENFORCED,
    ATTACHMENT_LINKS_MUST_MATCH_VISIT_AND_PATIENT_CONTEXT,
    PRINTABLE_SUMMARIES_MUST_EXCLUDE_INTERNAL_ONLY_METADATA,
    CROSS_TENANT_DOCUMENTATION_ACCESS_BLOCKED
}
