package com.homehealthcare.documentation.foundation;

public enum Epic8DocumentationTargetType {
    VISIT_NOTE_TEMPLATE,
    FORM_TEMPLATE,
    TASK_LIBRARY_ITEM,
    VISIT_DOCUMENTATION_RECORD,
    NOTE_FIELD_RESPONSE,
    TASK_COMPLETION_RESPONSE,
    DOCUMENTATION_ATTACHMENT_LINK,
    PRINTABLE_SUMMARY_PROJECTION
}
