package com.homehealthcare.security.authorization;

import com.homehealthcare.security.branch.AgencyRole;
import java.util.EnumSet;
import java.util.Set;

public enum AgencyPermission {
    VIEW_AGENCY_SETTINGS(false, AgencyRole.AGENCY_OWNER, AgencyRole.BRANCH_ADMIN),
    MANAGE_AGENCY_SETTINGS(true, AgencyRole.AGENCY_OWNER),
    VIEW_USER_DIRECTORY(false, AgencyRole.AGENCY_OWNER, AgencyRole.BRANCH_ADMIN),
    INVITE_USER(true, AgencyRole.AGENCY_OWNER, AgencyRole.BRANCH_ADMIN),
    EDIT_USER_PROFILE(true, AgencyRole.AGENCY_OWNER, AgencyRole.BRANCH_ADMIN),
    MANAGE_USER_STATUS(true, AgencyRole.AGENCY_OWNER, AgencyRole.BRANCH_ADMIN),
    MANAGE_AGENCY_MFA_POLICY(true, AgencyRole.AGENCY_OWNER, AgencyRole.BRANCH_ADMIN),
    VIEW_AUDIT_LOG(false, AgencyRole.AGENCY_OWNER, AgencyRole.BRANCH_ADMIN, AgencyRole.BILLING_BACK_OFFICE, AgencyRole.READ_ONLY_AUDITOR),
    VIEW_AGENCY_CONFIGURATION(false, AgencyRole.AGENCY_OWNER, AgencyRole.BRANCH_ADMIN),
    MANAGE_AGENCY_CONFIGURATION(true, AgencyRole.AGENCY_OWNER, AgencyRole.BRANCH_ADMIN),
    VIEW_TEMPLATE_CONFIGURATION(false, AgencyRole.AGENCY_OWNER, AgencyRole.BRANCH_ADMIN),
    MANAGE_TEMPLATE_CONFIGURATION(true, AgencyRole.AGENCY_OWNER, AgencyRole.BRANCH_ADMIN),
    VIEW_WORKFORCE_CONFIGURATION(false, AgencyRole.AGENCY_OWNER, AgencyRole.BRANCH_ADMIN),
    MANAGE_WORKFORCE_CONFIGURATION(true, AgencyRole.AGENCY_OWNER, AgencyRole.BRANCH_ADMIN),
    VIEW_BRANCH_POLICY(false,
            Set.of(AgencyRole.AGENCY_OWNER),
            Set.of(AgencyRole.BRANCH_ADMIN)),
    MANAGE_BRANCH_POLICY(true,
            Set.of(AgencyRole.AGENCY_OWNER),
            Set.of(AgencyRole.BRANCH_ADMIN)),
    VIEW_ALERT_RULE(false,
            Set.of(AgencyRole.AGENCY_OWNER),
            Set.of(AgencyRole.BRANCH_ADMIN)),
    MANAGE_ALERT_RULE(true,
            Set.of(AgencyRole.AGENCY_OWNER),
            Set.of(AgencyRole.BRANCH_ADMIN)),
    VIEW_COMPENSATION_SETTINGS(false, AgencyRole.AGENCY_OWNER, AgencyRole.BRANCH_ADMIN),
    MANAGE_COMPENSATION_SETTINGS(true, AgencyRole.AGENCY_OWNER, AgencyRole.BRANCH_ADMIN),
    VIEW_PATIENT_DIRECTORY(false, AgencyRole.AGENCY_OWNER, AgencyRole.BRANCH_ADMIN, AgencyRole.SCHEDULER_COORDINATOR, AgencyRole.QA_CLINICAL_REVIEWER),
    MANAGE_PATIENT_DEMOGRAPHICS(true, AgencyRole.AGENCY_OWNER, AgencyRole.BRANCH_ADMIN, AgencyRole.SCHEDULER_COORDINATOR),
    MANAGE_PATIENT_CONTACTS(true, AgencyRole.AGENCY_OWNER, AgencyRole.BRANCH_ADMIN, AgencyRole.SCHEDULER_COORDINATOR),
    MANAGE_PATIENT_ADDRESS(true, AgencyRole.AGENCY_OWNER, AgencyRole.BRANCH_ADMIN, AgencyRole.SCHEDULER_COORDINATOR),
    MANAGE_PATIENT_ELIGIBILITY(true, AgencyRole.AGENCY_OWNER, AgencyRole.BRANCH_ADMIN, AgencyRole.SCHEDULER_COORDINATOR),
    MANAGE_PATIENT_DIAGNOSES(true, AgencyRole.AGENCY_OWNER, AgencyRole.BRANCH_ADMIN, AgencyRole.QA_CLINICAL_REVIEWER),
    MANAGE_PATIENT_PAYER_LINKAGE(true, AgencyRole.AGENCY_OWNER, AgencyRole.BRANCH_ADMIN, AgencyRole.BILLING_BACK_OFFICE),
    MANAGE_PATIENT_AUTHORIZATIONS(true, AgencyRole.AGENCY_OWNER, AgencyRole.BRANCH_ADMIN, AgencyRole.SCHEDULER_COORDINATOR, AgencyRole.BILLING_BACK_OFFICE),
    VIEW_PATIENT_ATTACHMENTS(false, AgencyRole.AGENCY_OWNER, AgencyRole.BRANCH_ADMIN, AgencyRole.SCHEDULER_COORDINATOR, AgencyRole.QA_CLINICAL_REVIEWER, AgencyRole.BILLING_BACK_OFFICE),
    MANAGE_PATIENT_ATTACHMENTS(true, AgencyRole.AGENCY_OWNER, AgencyRole.BRANCH_ADMIN, AgencyRole.SCHEDULER_COORDINATOR, AgencyRole.QA_CLINICAL_REVIEWER),
    VIEW_WORKFORCE_DIRECTORY(false,
            Set.of(AgencyRole.AGENCY_OWNER),
            Set.of(AgencyRole.BRANCH_ADMIN, AgencyRole.SCHEDULER_COORDINATOR)),
    MANAGE_CAREGIVER_PROFILES(true,
            Set.of(AgencyRole.AGENCY_OWNER),
            Set.of(AgencyRole.BRANCH_ADMIN, AgencyRole.SCHEDULER_COORDINATOR)),
    MANAGE_CAREGIVER_CREDENTIALS(true,
            Set.of(AgencyRole.AGENCY_OWNER),
            Set.of(AgencyRole.BRANCH_ADMIN, AgencyRole.SCHEDULER_COORDINATOR)),
    MANAGE_CAREGIVER_AVAILABILITY(true,
            Set.of(AgencyRole.AGENCY_OWNER),
            Set.of(AgencyRole.BRANCH_ADMIN, AgencyRole.SCHEDULER_COORDINATOR)),
    MANAGE_CAREGIVER_UNAVAILABILITY(true,
            Set.of(AgencyRole.AGENCY_OWNER),
            Set.of(AgencyRole.BRANCH_ADMIN, AgencyRole.SCHEDULER_COORDINATOR)),
    VIEW_CAREGIVER_PERFORMANCE(false,
            Set.of(AgencyRole.AGENCY_OWNER),
            Set.of(AgencyRole.BRANCH_ADMIN, AgencyRole.SCHEDULER_COORDINATOR)),
    VIEW_SCHEDULING_WORKSPACE(false,
            Set.of(AgencyRole.AGENCY_OWNER),
            Set.of(AgencyRole.BRANCH_ADMIN, AgencyRole.SCHEDULER_COORDINATOR)),
    MANAGE_SCHEDULE_VISITS(true,
            Set.of(AgencyRole.AGENCY_OWNER),
            Set.of(AgencyRole.BRANCH_ADMIN, AgencyRole.SCHEDULER_COORDINATOR)),
    ASSIGN_CAREGIVERS(true,
            Set.of(AgencyRole.AGENCY_OWNER),
            Set.of(AgencyRole.BRANCH_ADMIN, AgencyRole.SCHEDULER_COORDINATOR)),
    MANAGE_OPEN_SHIFTS(true,
            Set.of(AgencyRole.AGENCY_OWNER),
            Set.of(AgencyRole.BRANCH_ADMIN, AgencyRole.SCHEDULER_COORDINATOR)),
    RESCHEDULE_VISITS(true,
            Set.of(AgencyRole.AGENCY_OWNER),
            Set.of(AgencyRole.BRANCH_ADMIN, AgencyRole.SCHEDULER_COORDINATOR)),
    CANCEL_VISITS(true,
            Set.of(AgencyRole.AGENCY_OWNER),
            Set.of(AgencyRole.BRANCH_ADMIN, AgencyRole.SCHEDULER_COORDINATOR)),
    VIEW_SCHEDULE_CONFLICTS(false,
            Set.of(AgencyRole.AGENCY_OWNER),
            Set.of(AgencyRole.BRANCH_ADMIN, AgencyRole.SCHEDULER_COORDINATOR)),
    VIEW_OWN_MOBILE_VISITS(false, AgencyRole.CAREGIVER),
    EXECUTE_OWN_VISITS(true, AgencyRole.CAREGIVER),
    SUBMIT_MOBILE_VISIT_DOCUMENTATION(true, AgencyRole.CAREGIVER),
    UPLOAD_MOBILE_VISIT_ARTIFACTS(true, AgencyRole.CAREGIVER),
    CREATE_MOBILE_INCIDENTS(true, AgencyRole.CAREGIVER),
    VIEW_MOBILE_MESSAGES(false, AgencyRole.CAREGIVER),
    SEND_MOBILE_MESSAGES(true, AgencyRole.CAREGIVER),
    VIEW_OWN_EVV(false, AgencyRole.CAREGIVER),
    SUBMIT_OWN_EVV(true, AgencyRole.CAREGIVER),
    MANAGE_EVV_EXCEPTIONS(true,
            Set.of(AgencyRole.AGENCY_OWNER),
            Set.of(AgencyRole.BRANCH_ADMIN, AgencyRole.SCHEDULER_COORDINATOR, AgencyRole.QA_CLINICAL_REVIEWER)),
    VIEW_MISSED_VISITS(false,
            Set.of(AgencyRole.AGENCY_OWNER),
            Set.of(AgencyRole.BRANCH_ADMIN, AgencyRole.SCHEDULER_COORDINATOR, AgencyRole.QA_CLINICAL_REVIEWER)),
    RESOLVE_MISSED_VISITS(true,
            Set.of(AgencyRole.AGENCY_OWNER),
            Set.of(AgencyRole.BRANCH_ADMIN, AgencyRole.SCHEDULER_COORDINATOR, AgencyRole.QA_CLINICAL_REVIEWER)),
    RECEIVE_EVV_NOTIFICATIONS(false,
            Set.of(AgencyRole.AGENCY_OWNER),
            Set.of(AgencyRole.BRANCH_ADMIN, AgencyRole.SCHEDULER_COORDINATOR, AgencyRole.QA_CLINICAL_REVIEWER)),
    VIEW_DOCUMENTATION_WORKSPACE(false,
            Set.of(AgencyRole.AGENCY_OWNER),
            Set.of(AgencyRole.BRANCH_ADMIN, AgencyRole.SCHEDULER_COORDINATOR, AgencyRole.QA_CLINICAL_REVIEWER, AgencyRole.CAREGIVER, AgencyRole.BILLING_BACK_OFFICE)),
    MANAGE_DOCUMENTATION_TEMPLATES(true,
            Set.of(AgencyRole.AGENCY_OWNER),
            Set.of(AgencyRole.BRANCH_ADMIN)),
    MANAGE_DOCUMENTATION_TASK_LIBRARY(true,
            Set.of(AgencyRole.AGENCY_OWNER),
            Set.of(AgencyRole.BRANCH_ADMIN)),
    VIEW_VISIT_DOCUMENTATION(false,
            Set.of(AgencyRole.AGENCY_OWNER, AgencyRole.BILLING_BACK_OFFICE),
            Set.of(AgencyRole.BRANCH_ADMIN, AgencyRole.SCHEDULER_COORDINATOR, AgencyRole.QA_CLINICAL_REVIEWER, AgencyRole.CAREGIVER)),
    DRAFT_VISIT_DOCUMENTATION(true,
            Set.of(AgencyRole.AGENCY_OWNER),
            Set.of(AgencyRole.BRANCH_ADMIN, AgencyRole.SCHEDULER_COORDINATOR, AgencyRole.CAREGIVER)),
    SUBMIT_VISIT_DOCUMENTATION(true,
            Set.of(AgencyRole.AGENCY_OWNER),
            Set.of(AgencyRole.BRANCH_ADMIN, AgencyRole.SCHEDULER_COORDINATOR, AgencyRole.CAREGIVER)),
    AMEND_VISIT_DOCUMENTATION(true,
            Set.of(AgencyRole.AGENCY_OWNER),
            Set.of(AgencyRole.BRANCH_ADMIN, AgencyRole.QA_CLINICAL_REVIEWER)),
    GENERATE_PRINTABLE_DOCUMENTATION_SUMMARY(false,
            Set.of(AgencyRole.AGENCY_OWNER, AgencyRole.BILLING_BACK_OFFICE),
            Set.of(AgencyRole.BRANCH_ADMIN, AgencyRole.SCHEDULER_COORDINATOR, AgencyRole.QA_CLINICAL_REVIEWER)),
    VIEW_MESSAGING_WORKSPACE(false,
            Set.of(AgencyRole.AGENCY_OWNER),
            Set.of(AgencyRole.BRANCH_ADMIN, AgencyRole.SCHEDULER_COORDINATOR, AgencyRole.QA_CLINICAL_REVIEWER, AgencyRole.CAREGIVER)),
    SEND_SECURE_MESSAGES(true,
            Set.of(AgencyRole.AGENCY_OWNER),
            Set.of(AgencyRole.BRANCH_ADMIN, AgencyRole.SCHEDULER_COORDINATOR, AgencyRole.QA_CLINICAL_REVIEWER, AgencyRole.CAREGIVER)),
    MANAGE_STAFF_GROUPS(true,
            Set.of(AgencyRole.AGENCY_OWNER),
            Set.of(AgencyRole.BRANCH_ADMIN)),
    SEND_BRANCH_BROADCASTS(true,
            Set.of(AgencyRole.AGENCY_OWNER),
            Set.of(AgencyRole.BRANCH_ADMIN, AgencyRole.SCHEDULER_COORDINATOR)),
    MANAGE_MESSAGE_ESCALATIONS(true,
            Set.of(AgencyRole.AGENCY_OWNER),
            Set.of(AgencyRole.BRANCH_ADMIN, AgencyRole.SCHEDULER_COORDINATOR, AgencyRole.QA_CLINICAL_REVIEWER)),
    VIEW_REVIEW_WORKSPACE(false,
            Set.of(AgencyRole.AGENCY_OWNER),
            Set.of(AgencyRole.BRANCH_ADMIN, AgencyRole.QA_CLINICAL_REVIEWER)),
    VIEW_EXCEPTION_QUEUE(false,
            Set.of(AgencyRole.AGENCY_OWNER),
            Set.of(AgencyRole.BRANCH_ADMIN, AgencyRole.QA_CLINICAL_REVIEWER)),
    ASSIGN_REVIEW_WORK(true,
            Set.of(AgencyRole.AGENCY_OWNER),
            Set.of(AgencyRole.BRANCH_ADMIN, AgencyRole.QA_CLINICAL_REVIEWER)),
    PERFORM_REVIEW_DECISIONS(true,
            Set.of(AgencyRole.AGENCY_OWNER),
            Set.of(AgencyRole.BRANCH_ADMIN, AgencyRole.QA_CLINICAL_REVIEWER)),
    REQUEST_REVIEW_SIGNOFF(true,
            Set.of(AgencyRole.AGENCY_OWNER),
            Set.of(AgencyRole.BRANCH_ADMIN, AgencyRole.QA_CLINICAL_REVIEWER)),
    VIEW_REVIEW_AUDIT_CONTEXT(false,
            Set.of(AgencyRole.AGENCY_OWNER, AgencyRole.READ_ONLY_AUDITOR),
            Set.of(AgencyRole.BRANCH_ADMIN, AgencyRole.QA_CLINICAL_REVIEWER)),
    VIEW_COMPLIANCE_WORKSPACE(false,
            Set.of(AgencyRole.AGENCY_OWNER, AgencyRole.READ_ONLY_AUDITOR),
            Set.of(AgencyRole.BRANCH_ADMIN, AgencyRole.QA_CLINICAL_REVIEWER)),
    VIEW_COMPLIANCE_DASHBOARD(false,
            Set.of(AgencyRole.AGENCY_OWNER, AgencyRole.READ_ONLY_AUDITOR),
            Set.of(AgencyRole.BRANCH_ADMIN, AgencyRole.QA_CLINICAL_REVIEWER)),
    MANAGE_COMPLIANCE_CHECKLISTS(true,
            Set.of(AgencyRole.AGENCY_OWNER),
            Set.of(AgencyRole.BRANCH_ADMIN, AgencyRole.QA_CLINICAL_REVIEWER)),
    MANAGE_REQUIRED_DOCUMENTATION_RULES(true,
            Set.of(AgencyRole.AGENCY_OWNER),
            Set.of(AgencyRole.BRANCH_ADMIN, AgencyRole.QA_CLINICAL_REVIEWER)),
    MANAGE_PATIENT_ACKNOWLEDGMENTS(true,
            Set.of(AgencyRole.AGENCY_OWNER),
            Set.of(AgencyRole.BRANCH_ADMIN, AgencyRole.QA_CLINICAL_REVIEWER)),
    MANAGE_CERTIFICATION_PERIODS(true,
            Set.of(AgencyRole.AGENCY_OWNER),
            Set.of(AgencyRole.BRANCH_ADMIN, AgencyRole.QA_CLINICAL_REVIEWER)),
    MANAGE_PATIENT_RISK_REMINDERS(true,
            Set.of(AgencyRole.AGENCY_OWNER),
            Set.of(AgencyRole.BRANCH_ADMIN, AgencyRole.QA_CLINICAL_REVIEWER)),
    RECALCULATE_COMPLIANCE_STATUS(true,
            Set.of(AgencyRole.AGENCY_OWNER),
            Set.of(AgencyRole.BRANCH_ADMIN, AgencyRole.QA_CLINICAL_REVIEWER)),
    VIEW_PATIENT_EVENT_WORKSPACE(false,
            Set.of(AgencyRole.AGENCY_OWNER, AgencyRole.READ_ONLY_AUDITOR),
            Set.of(AgencyRole.BRANCH_ADMIN, AgencyRole.SCHEDULER_COORDINATOR, AgencyRole.QA_CLINICAL_REVIEWER)),
    CREATE_INCIDENT_RECORDS(true,
            Set.of(AgencyRole.AGENCY_OWNER),
            Set.of(AgencyRole.BRANCH_ADMIN, AgencyRole.SCHEDULER_COORDINATOR, AgencyRole.QA_CLINICAL_REVIEWER, AgencyRole.CAREGIVER)),
    MANAGE_INFECTION_RECORDS(true,
            Set.of(AgencyRole.AGENCY_OWNER),
            Set.of(AgencyRole.BRANCH_ADMIN, AgencyRole.QA_CLINICAL_REVIEWER)),
    MANAGE_WOUND_RECORDS(true,
            Set.of(AgencyRole.AGENCY_OWNER),
            Set.of(AgencyRole.BRANCH_ADMIN, AgencyRole.QA_CLINICAL_REVIEWER)),
    LINK_PATIENT_EVENT_EVIDENCE(true,
            Set.of(AgencyRole.AGENCY_OWNER),
            Set.of(AgencyRole.BRANCH_ADMIN, AgencyRole.SCHEDULER_COORDINATOR, AgencyRole.QA_CLINICAL_REVIEWER, AgencyRole.CAREGIVER)),
    ASSIGN_PATIENT_EVENT_FOLLOW_UP(true,
            Set.of(AgencyRole.AGENCY_OWNER),
            Set.of(AgencyRole.BRANCH_ADMIN, AgencyRole.SCHEDULER_COORDINATOR, AgencyRole.QA_CLINICAL_REVIEWER)),
    ESCALATE_PATIENT_EVENTS(true,
            Set.of(AgencyRole.AGENCY_OWNER),
            Set.of(AgencyRole.BRANCH_ADMIN, AgencyRole.SCHEDULER_COORDINATOR, AgencyRole.QA_CLINICAL_REVIEWER)),
    RESOLVE_PATIENT_EVENTS(true,
            Set.of(AgencyRole.AGENCY_OWNER),
            Set.of(AgencyRole.BRANCH_ADMIN, AgencyRole.QA_CLINICAL_REVIEWER)),
    VIEW_GOAL_WORKSPACE(false,
            Set.of(AgencyRole.AGENCY_OWNER, AgencyRole.READ_ONLY_AUDITOR),
            Set.of(AgencyRole.BRANCH_ADMIN, AgencyRole.QA_CLINICAL_REVIEWER, AgencyRole.CAREGIVER)),
    MANAGE_GOAL_TEMPLATES(true,
            Set.of(AgencyRole.AGENCY_OWNER),
            Set.of(AgencyRole.BRANCH_ADMIN, AgencyRole.QA_CLINICAL_REVIEWER)),
    MANAGE_PATIENT_GOALS(true,
            Set.of(AgencyRole.AGENCY_OWNER),
            Set.of(AgencyRole.BRANCH_ADMIN, AgencyRole.QA_CLINICAL_REVIEWER)),
    MANAGE_GOAL_INTERVENTIONS(true,
            Set.of(AgencyRole.AGENCY_OWNER),
            Set.of(AgencyRole.BRANCH_ADMIN, AgencyRole.QA_CLINICAL_REVIEWER)),
    ADD_GOAL_PROGRESS_NOTES(true,
            Set.of(AgencyRole.AGENCY_OWNER),
            Set.of(AgencyRole.BRANCH_ADMIN, AgencyRole.QA_CLINICAL_REVIEWER, AgencyRole.CAREGIVER)),
    MANAGE_GOAL_STATE_TRANSITIONS(true,
            Set.of(AgencyRole.AGENCY_OWNER),
            Set.of(AgencyRole.BRANCH_ADMIN, AgencyRole.QA_CLINICAL_REVIEWER)),
    MANAGE_CAREPLAN_SYNC(true,
            Set.of(AgencyRole.AGENCY_OWNER),
            Set.of(AgencyRole.BRANCH_ADMIN, AgencyRole.QA_CLINICAL_REVIEWER)),
    VIEW_REVENUE_READINESS_WORKSPACE(false,
            Set.of(AgencyRole.AGENCY_OWNER, AgencyRole.READ_ONLY_AUDITOR),
            Set.of(AgencyRole.BRANCH_ADMIN, AgencyRole.BILLING_BACK_OFFICE, AgencyRole.QA_CLINICAL_REVIEWER)),
    RECALCULATE_REVENUE_READINESS(true,
            Set.of(AgencyRole.AGENCY_OWNER),
            Set.of(AgencyRole.BRANCH_ADMIN, AgencyRole.BILLING_BACK_OFFICE, AgencyRole.QA_CLINICAL_REVIEWER)),
    MANAGE_REVENUE_EXCEPTION_FLAGS(true,
            Set.of(AgencyRole.AGENCY_OWNER),
            Set.of(AgencyRole.BRANCH_ADMIN, AgencyRole.BILLING_BACK_OFFICE, AgencyRole.QA_CLINICAL_REVIEWER)),
    GENERATE_REVENUE_EXPORTS(true,
            Set.of(AgencyRole.AGENCY_OWNER),
            Set.of(AgencyRole.BRANCH_ADMIN, AgencyRole.BILLING_BACK_OFFICE)),
    VIEW_AUTHORIZATION_USAGE_SUMMARIES(false,
            Set.of(AgencyRole.AGENCY_OWNER, AgencyRole.READ_ONLY_AUDITOR),
            Set.of(AgencyRole.BRANCH_ADMIN, AgencyRole.BILLING_BACK_OFFICE, AgencyRole.QA_CLINICAL_REVIEWER)),
    VIEW_PAYER_SERVICE_SUMMARIES(false,
            Set.of(AgencyRole.AGENCY_OWNER, AgencyRole.READ_ONLY_AUDITOR),
            Set.of(AgencyRole.BRANCH_ADMIN, AgencyRole.BILLING_BACK_OFFICE, AgencyRole.QA_CLINICAL_REVIEWER)),
    VIEW_ANALYTICS_WORKSPACE(false,
            Set.of(AgencyRole.AGENCY_OWNER, AgencyRole.READ_ONLY_AUDITOR),
            Set.of(AgencyRole.BRANCH_ADMIN, AgencyRole.SCHEDULER_COORDINATOR, AgencyRole.BILLING_BACK_OFFICE, AgencyRole.QA_CLINICAL_REVIEWER)),
    VIEW_BRANCH_PERFORMANCE_METRICS(false,
            Set.of(AgencyRole.AGENCY_OWNER, AgencyRole.READ_ONLY_AUDITOR),
            Set.of(AgencyRole.BRANCH_ADMIN, AgencyRole.SCHEDULER_COORDINATOR, AgencyRole.BILLING_BACK_OFFICE, AgencyRole.QA_CLINICAL_REVIEWER)),
    VIEW_CAREGIVER_UTILIZATION_METRICS(false,
            Set.of(AgencyRole.AGENCY_OWNER, AgencyRole.READ_ONLY_AUDITOR),
            Set.of(AgencyRole.BRANCH_ADMIN, AgencyRole.SCHEDULER_COORDINATOR, AgencyRole.QA_CLINICAL_REVIEWER)),
    VIEW_QA_BACKLOG_METRICS(false,
            Set.of(AgencyRole.AGENCY_OWNER, AgencyRole.READ_ONLY_AUDITOR),
            Set.of(AgencyRole.BRANCH_ADMIN, AgencyRole.QA_CLINICAL_REVIEWER)),
    VIEW_REVENUE_READINESS_METRICS(false,
            Set.of(AgencyRole.AGENCY_OWNER, AgencyRole.READ_ONLY_AUDITOR),
            Set.of(AgencyRole.BRANCH_ADMIN, AgencyRole.BILLING_BACK_OFFICE, AgencyRole.QA_CLINICAL_REVIEWER)),
    VIEW_COMPLIANCE_EXCEPTION_METRICS(false,
            Set.of(AgencyRole.AGENCY_OWNER, AgencyRole.READ_ONLY_AUDITOR),
            Set.of(AgencyRole.BRANCH_ADMIN, AgencyRole.BILLING_BACK_OFFICE, AgencyRole.QA_CLINICAL_REVIEWER)),
    REFRESH_DASHBOARD_METRICS(true,
            Set.of(AgencyRole.AGENCY_OWNER),
            Set.of(AgencyRole.BRANCH_ADMIN, AgencyRole.SCHEDULER_COORDINATOR, AgencyRole.BILLING_BACK_OFFICE, AgencyRole.QA_CLINICAL_REVIEWER)),
    VIEW_BRANCH(false,
            Set.of(AgencyRole.AGENCY_OWNER, AgencyRole.BILLING_BACK_OFFICE, AgencyRole.READ_ONLY_AUDITOR),
            Set.of(AgencyRole.BRANCH_ADMIN, AgencyRole.SCHEDULER_COORDINATOR, AgencyRole.CAREGIVER, AgencyRole.QA_CLINICAL_REVIEWER)),
    EDIT_BRANCH(true,
            Set.of(AgencyRole.AGENCY_OWNER),
            Set.of(AgencyRole.BRANCH_ADMIN));

    private final boolean sensitive;
    private final Set<AgencyRole> agencyWideRoles;
    private final Set<AgencyRole> branchScopedRoles;

    AgencyPermission(boolean sensitive, AgencyRole... allowedRoles) {
        this.sensitive = sensitive;
        this.agencyWideRoles = EnumSet.of(allowedRoles[0], allowedRoles);
        this.branchScopedRoles = Set.of();
    }

    AgencyPermission(boolean sensitive, Set<AgencyRole> agencyWideRoles, Set<AgencyRole> branchScopedRoles) {
        this.sensitive = sensitive;
        this.agencyWideRoles = EnumSet.copyOf(agencyWideRoles);
        this.branchScopedRoles = EnumSet.copyOf(branchScopedRoles);
    }

    public boolean isSensitive() {
        return sensitive;
    }

    public boolean isAllowedFor(AgencyRole role) {
        return agencyWideRoles.contains(role) || branchScopedRoles.contains(role);
    }

    public boolean isAgencyWideFor(AgencyRole role) {
        return agencyWideRoles.contains(role);
    }

    public boolean requiresAssignedBranchFor(AgencyRole role) {
        return branchScopedRoles.contains(role);
    }
}
