package com.homehealthcare.careprogression.foundation;

public enum CareProgressionOperationGuardrail {
    CROSS_TENANT_GOAL_ACCESS_BLOCKED,
    CROSS_BRANCH_GOAL_ACCESS_BLOCKED,
    GOAL_STATE_TRANSITIONS_MUST_PRESERVE_VERSION_HISTORY,
    PROGRESS_NOTES_MUST_APPEND_INSTEAD_OF_OVERWRITE,
    CAREPLAN_SYNC_MUST_NOT_CORRUPT_HISTORICAL_GOAL_VERSIONS,
    PROGRESSION_SUMMARIES_MUST_EXCLUDE_EXCESS_PATIENT_DETAIL
}
