package com.homehealthcare.careprogression.foundation;

public enum Epic13CareProgressionAuditAction {
    GOAL_TEMPLATE_SAVED("CARE_PROGRESSION_GOAL_TEMPLATE_SAVED"),
    PATIENT_GOAL_CREATED("CARE_PROGRESSION_PATIENT_GOAL_CREATED"),
    PATIENT_GOAL_UPDATED("CARE_PROGRESSION_PATIENT_GOAL_UPDATED"),
    INTERVENTION_SAVED("CARE_PROGRESSION_INTERVENTION_SAVED"),
    PROGRESS_NOTE_ADDED("CARE_PROGRESSION_PROGRESS_NOTE_ADDED"),
    GOAL_STATE_CHANGED("CARE_PROGRESSION_GOAL_STATE_CHANGED"),
    TARGET_DATE_CHANGED("CARE_PROGRESSION_TARGET_DATE_CHANGED"),
    GOAL_VERSION_RECORDED("CARE_PROGRESSION_GOAL_VERSION_RECORDED"),
    CAREPLAN_SYNC_UPDATED("CARE_PROGRESSION_CAREPLAN_SYNC_UPDATED"),
    PROGRESSION_EVENT_PUBLISHED("CARE_PROGRESSION_EVENT_PUBLISHED");

    private final String actionType;

    Epic13CareProgressionAuditAction(String actionType) {
        this.actionType = actionType;
    }

    public String actionType() {
        return actionType;
    }
}
