package com.homehealthcare.evv.foundation;

public enum Epic7EvvTargetType {
    EVV_VERIFICATION_SESSION,
    EVV_CLOCK_EVENT,
    GEOFENCE_EVALUATION,
    SIGNATURE_VERIFICATION_LINK,
    MISSED_VISIT_RECORD,
    VISIT_EXCEPTION_RECORD,
    SUPERVISOR_NOTIFICATION_EVENT,
    ESCALATION_REQUEST
}
