package com.homehealthcare.evv.foundation;

public enum EvvOperationGuardrail {
    CROSS_TENANT_EVV_ACCESS_BLOCKED,
    CROSS_BRANCH_EVV_REVIEW_BLOCKED,
    ONLY_ASSIGNED_CAREGIVER_CAN_SUBMIT_OWN_EVV,
    DUPLICATE_CLOCK_EVENT_REQUIRES_EXPLICIT_RESOLUTION,
    GEOFENCE_EVALUATION_MUST_USE_APPROVED_LOCATION_CONTEXT,
    MISSING_SIGNATURE_REQUIREMENTS_MUST_NOT_BE_SILENTLY_IGNORED,
    MISSED_VISITS_MUST_CREATE_DURABLE_EXCEPTION_HISTORY,
    EVV_PAYLOADS_MUST_EXCLUDE_INTERNAL_DEVICE_SECRETS
}
