package com.homehealthcare.analytics.foundation;

public enum AnalyticsOperationGuardrail {
    MINIMIZE_PHI_IN_SUMMARY_VIEWS,
    ENFORCE_BRANCH_AWARE_VISIBILITY,
    DERIVE_FROM_APPROVED_SOURCE_DOMAINS,
    DISTINGUISH_NEAR_REAL_TIME_AND_REFRESHED_METRICS,
    RECORD_REFRESH_ACTIVITY_IN_AUDIT_LOG
}
