package com.homehealthcare.analytics.foundation;

public enum Epic15AnalyticsTargetType {
    DASHBOARD_METRIC_DEFINITION,
    DASHBOARD_METRIC_SNAPSHOT,
    BRANCH_PERFORMANCE_SUMMARY,
    UTILIZATION_SUMMARY,
    BACKLOG_SUMMARY,
    READINESS_COMPLIANCE_SUMMARY,
    METRIC_TREND_SNAPSHOT,
    DASHBOARD_REFRESH_REQUEST
}
