package com.homehealthcare.analytics.foundation;

public enum Epic15AnalyticsAuditAction {
    DASHBOARD_SNAPSHOT_GENERATED("ANALYTICS_DASHBOARD_SNAPSHOT_GENERATED"),
    METRIC_REFRESH_TRIGGERED("ANALYTICS_METRIC_REFRESH_TRIGGERED"),
    BRANCH_PERFORMANCE_REFRESHED("ANALYTICS_BRANCH_PERFORMANCE_REFRESHED"),
    UTILIZATION_SUMMARY_REFRESHED("ANALYTICS_UTILIZATION_SUMMARY_REFRESHED"),
    QA_BACKLOG_SUMMARY_REFRESHED("ANALYTICS_QA_BACKLOG_SUMMARY_REFRESHED"),
    REVENUE_READINESS_SUMMARY_REFRESHED("ANALYTICS_REVENUE_READINESS_SUMMARY_REFRESHED"),
    COMPLIANCE_SUMMARY_REFRESHED("ANALYTICS_COMPLIANCE_SUMMARY_REFRESHED");

    private final String actionType;

    Epic15AnalyticsAuditAction(String actionType) {
        this.actionType = actionType;
    }

    public String actionType() {
        return actionType;
    }
}
