package com.homehealthcare.mobile.foundation;

public enum Epic6MobileAuditAction {
    MOBILE_SESSION_BOOTSTRAPPED("MOBILE_SESSION_BOOTSTRAPPED"),
    VISIT_EXECUTION_STARTED("MOBILE_VISIT_EXECUTION_STARTED"),
    VISIT_EXECUTION_ENDED("MOBILE_VISIT_EXECUTION_ENDED"),
    TASK_CHECKLIST_SAVED("MOBILE_TASK_CHECKLIST_SAVED"),
    QUICK_NOTE_SAVED("MOBILE_QUICK_NOTE_SAVED"),
    PHOTO_UPLOADED("MOBILE_PHOTO_UPLOADED"),
    SIGNATURE_CAPTURED("MOBILE_SIGNATURE_CAPTURED"),
    INCIDENT_FLAGGED("MOBILE_INCIDENT_FLAGGED"),
    MESSAGE_SENT("MOBILE_MESSAGE_SENT"),
    OFFLINE_SYNC_ACCEPTED("MOBILE_OFFLINE_SYNC_ACCEPTED"),
    OFFLINE_SYNC_REJECTED("MOBILE_OFFLINE_SYNC_REJECTED");

    private final String actionType;

    Epic6MobileAuditAction(String actionType) {
        this.actionType = actionType;
    }

    public String actionType() {
        return actionType;
    }
}
