package com.homehealthcare.mobile.foundation;

public enum MobileExecutionEntityCategory {
    MOBILE_DEVICE_SESSION,
    TODAY_WORK_QUERY,
    VISIT_EXECUTION_SESSION,
    ROUTE_STOP_PROJECTION,
    PATIENT_SUMMARY_SNAPSHOT,
    CARE_INSTRUCTION_SNAPSHOT,
    TASK_CHECKLIST_ENTRY,
    QUICK_NOTE_ENTRY,
    FIELD_PHOTO_ARTIFACT,
    FIELD_SIGNATURE_ARTIFACT,
    INCIDENT_REPORT,
    MESSAGE_THREAD_SUMMARY,
    OFFLINE_SYNC_ENVELOPE
}
