package com.homehealthcare.mobile.foundation;

public enum MobileOperationGuardrail {
    ONLY_ASSIGNED_CAREGIVER_CAN_OPEN_VISIT,
    ONLY_ONE_ACTIVE_EXECUTION_SESSION_PER_VISIT,
    COMPLETED_VISIT_CANNOT_BE_REOPENED_WITHOUT_APPROVED_WORKFLOW,
    OFFLINE_MUTATIONS_MUST_BE_IDEMPOTENT,
    CROSS_TENANT_MOBILE_ACCESS_BLOCKED,
    SELF_CONTEXT_ONLY_UNLESS_ELEVATED_SUPPORT_EXISTS,
    MOBILE_PAYLOADS_MUST_EXCLUDE_ADMIN_ONLY_FIELDS,
    SIGNATURE_AND_PHOTO_UPLOADS_REQUIRE_CONTROLLED_STORAGE_RULES
}
