package com.homehealthcare.messaging.foundation;

public enum MessagingOperationGuardrail {
    THREAD_PARTICIPANTS_MUST_SHARE_TENANT,
    CONTEXT_LINKS_MUST_SHARE_TENANT,
    BRANCH_BROADCAST_TARGET_MUST_MATCH_BRANCH_SCOPE,
    CROSS_BRANCH_THREAD_ACCESS_BLOCKED,
    EXTERNAL_CHANNEL_DELIVERY_OUT_OF_SCOPE,
    MESSAGE_BODY_NOT_EXPORTED_IN_AUDIT_METADATA
}
