package com.homehealthcare.revenuereadiness.foundation;

public enum RevenueOperationGuardrail {
    REQUIRES_BRANCH_SCOPED_VISIT_CONTEXT,
    REQUIRES_DETERMINISTIC_SOURCE_PROJECTIONS,
    REQUIRES_AUDITABLE_RECALCULATION,
    REQUIRES_CONTROLLED_EXPORT_GENERATION,
    REQUIRES_MINIMUM_FINANCIAL_CONTEXT_EXPOSURE
}
