package com.homehealthcare.revenuereadiness.foundation;

public enum RevenueReadinessEntityCategory {
    REVENUE_READINESS_PROJECTION,
    READINESS_VALIDATION_RESULT,
    REVENUE_EXCEPTION_FLAG,
    PAYROLL_EXPORT_ROW,
    INVOICE_EXPORT_ROW,
    AUTHORIZATION_USAGE_SNAPSHOT,
    PAYER_SERVICE_SUMMARY_PROJECTION
}
