package com.homehealthcare.workforce.foundation;

public enum Epic4WorkforceTargetType {
    CAREGIVER_PROFILE,
    CAREGIVER_CREDENTIAL,
    CAREGIVER_LANGUAGE,
    CAREGIVER_SKILL,
    CAREGIVER_GEOGRAPHY_PREFERENCE,
    CAREGIVER_SHIFT_PREFERENCE,
    CAREGIVER_AVAILABILITY,
    CAREGIVER_UNAVAILABILITY,
    CAREGIVER_PERFORMANCE_SUMMARY
}
