package com.homehealthcare.workforce.foundation;

public enum WorkforceOperationGuardrail {
    ONE_ACTIVE_PROFILE_PER_MEMBERSHIP,
    NO_OVERLAPPING_AVAILABILITY_CONFLICTS,
    NO_OVERLAPPING_UNAVAILABILITY_CONFLICTS,
    BRANCH_SCOPED_WORKFORCE_ACCESS_REQUIRES_ASSIGNED_BRANCH,
    PERFORMANCE_INDICATORS_ARE_DERIVED_NOT_USER_EDITED
}
