package com.homehealthcare.scheduling.foundation;

public enum Epic5SchedulingTargetType {
    VISIT_OCCURRENCE,
    RECURRING_VISIT_RULE,
    CAREGIVER_ASSIGNMENT,
    OPEN_SHIFT,
    RESCHEDULE_EVENT,
    CANCELLATION_EVENT,
    MATCH_EVALUATION,
    CONFLICT_EVALUATION,
    TRAVEL_AWARENESS_EVALUATION
}
