package com.homehealthcare.scheduling.foundation;

public enum SchedulingOperationGuardrail {
    INACTIVE_CAREGIVER_CANNOT_BE_ASSIGNED,
    CANCELLED_VISIT_CANNOT_REMAIN_ASSIGNED,
    OUT_OF_SCOPE_BRANCH_MUTATION_BLOCKED,
    CROSS_TENANT_SCHEDULE_ACCESS_BLOCKED,
    OVERLAP_CHECK_REQUIRED,
    OVERTIME_CHECK_REQUIRED,
    TRAVEL_AWARENESS_REQUIRED,
    RECURRENCE_HISTORY_MUST_BE_PRESERVED
}
