package com.homehealthcare.patientevent.foundation;

public enum Epic12PatientEventAuditAction {
    INCIDENT_CREATED("PATIENT_EVENT_INCIDENT_CREATED"),
    INCIDENT_UPDATED("PATIENT_EVENT_INCIDENT_UPDATED"),
    INFECTION_CREATED("PATIENT_EVENT_INFECTION_CREATED"),
    INFECTION_UPDATED("PATIENT_EVENT_INFECTION_UPDATED"),
    WOUND_CREATED("PATIENT_EVENT_WOUND_CREATED"),
    WOUND_UPDATED("PATIENT_EVENT_WOUND_UPDATED"),
    WOUND_HISTORY_ADDED("PATIENT_EVENT_WOUND_HISTORY_ADDED"),
    EVIDENCE_LINKED("PATIENT_EVENT_EVIDENCE_LINKED"),
    EVIDENCE_UNLINKED("PATIENT_EVENT_EVIDENCE_UNLINKED"),
    FOLLOW_UP_ASSIGNED("PATIENT_EVENT_FOLLOW_UP_ASSIGNED"),
    FOLLOW_UP_UPDATED("PATIENT_EVENT_FOLLOW_UP_UPDATED"),
    LONGITUDINAL_HISTORY_PROJECTED("PATIENT_EVENT_LONGITUDINAL_HISTORY_PROJECTED"),
    ESCALATION_CREATED("PATIENT_EVENT_ESCALATION_CREATED"),
    ESCALATION_CLEARED("PATIENT_EVENT_ESCALATION_CLEARED"),
    RECORD_RESOLVED("PATIENT_EVENT_RECORD_RESOLVED");

    private final String actionType;

    Epic12PatientEventAuditAction(String actionType) {
        this.actionType = actionType;
    }

    public String actionType() {
        return actionType;
    }
}
