package com.homehealthcare.patientevent.foundation;

public enum PatientEventOperationGuardrail {
    PATIENT_AND_BRANCH_SCOPED,
    MINIMUM_NECESSARY_PATIENT_CONTEXT_ONLY,
    EVIDENCE_LINKS_REFERENCE_EXISTING_ATTACHMENT_STORES,
    FOLLOW_UP_AND_ESCALATION_CHANGES_AUDITED,
    LONGITUDINAL_HISTORY_APPEND_ONLY,
    ALERT_EVENT_TYPES_STABLE
}
