package com.homehealthcare.review.foundation;

public enum ReviewOperationGuardrail {
    CROSS_TENANT_REVIEW_ACCESS_BLOCKED,
    CROSS_BRANCH_REVIEW_ASSIGNMENT_BLOCKED,
    REVIEW_DECISIONS_REQUIRE_AUTHORIZED_ASSIGNMENT_CONTEXT,
    RETURN_FOR_FIX_MUST_PRESERVE_FINDING_HISTORY,
    SIGNOFF_REQUESTS_MUST_NOT_SKIP_REVIEW_AUDIT,
    REVIEW_SUMMARIES_MUST_EXCLUDE_EXCESS_PATIENT_DETAIL
}
